apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-conn
spec:
  replicas: 8
  template:
    spec:
      containers:
      - name: curl-target
        image: devkimbob/html_conn:1.2.0
  strategy: RollingUpdate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
