apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-conn
spec:
  revisionHistoryLimit: 1
  replicas: 2
  template:
    # metadata:
    #   annotations:
    #     force-update: "true"
    spec:
      containers:
      - name: curl-target
        image: devkimbob/html_conn:latest
        # imagePullPolicy: Always
