apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-conn
spec:
  revisionHistoryLimit: 1
  replicas: 2
  template:
    spec:
      containers:
      - name: curl-target
        image: devkimbob/html_conn:latest
  strategy:
    type: Recreate
